16 - Matrix Fail Test

diff --git a/.github/workflows/test16.yml b/.github/workflows/test16.yml
--- a/.github/workflows/test16.yml
+++ b/.github/workflows/test16.yml
@@ -8,17 +8,32 @@ jobs:
     name: ${{matrix.os}}-${{matrix.node-version}}
     runs-on: ${{matrix.os}}
     strategy:
+      fail-fast: false
       matrix:
         node-version: [18.x, 20.x, 21.x]
         os:
           - ubuntu-latest
           - windows-latest
+        include:
+          - os: ubuntu-latest
+            node-version: 16.x
+          - os: ubuntu-latest
+            node-version: 21.x
+            tag: experimental
     steps:
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version: ${{matrix.node-version}}
+      - name: Fail Test strategy
+        if: matrix.tag == 'experimental'
+        run: |
+          echo "Failing strategy experimental"
+          exit 1
       - name: Perform Tests
         run: |
           echo "Running npm run test && npm run jest "
           echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
+          sleep 10
+      - name: Upload test results
+        run: echo 'uploading test results...'
